### ISSUE TITLE
Inconsistency in member count

### ISSUE THREAD

**Issue by streety** [toldani/sm-transition#4]
http://35.185.63.230/talk/memberlist.php?mode=team indicates jester, Melgar, and Polverone are in the group 'Registered COPPA users' but in the admin interface ('Users and groups' > 'Manage groups') that group has 0 members.

The memberlist shows 7812 members but in the admin interface the largest group is 'Registered users' with just 888 members.

**Comment by toldani** [comment]
That was supposed to be the admins group, so if you check it again, it's how it should be.  As for why so many users aren't in a group, that's strange.  I think it must be that group statistics are in a table that I don't access much, that's updated periodically.

**Comment by toldani** [comment]
Okay, turns out that groups are set in the sm_user_group table, since a user can be in multiple groups.  Each user has a group_id field, but that just determines their _primary_ group.  When modifying the database directly, it's possible for a user's primary group to be a group that they aren't actually in, and numbers shown in various places derive from different sources.  I added two lines of Ruby code to the commands.txt file that can add every user in the users table to the "registered users" group, if they aren't already in it.
